posey_ultimateblog_blog:
    path: /blog
    defaults: { _controller: posey.ultimateblog.controller:blog }

posey_ultimateblog_blog_display:
    path: /blog/{blog_id}
    defaults: { _controller: posey.ultimateblog.controller:blog_display }
    requirements:
        "blog_id": \d+

posey_ultimateblog_comment:
    path: /blog/{blog_id}/comment
    defaults: { _controller: posey.ultimateblog.controller:comment }
    requirements:
        "blog_id": \d+

posey_ultimateblog_categories:
    path: /blog/categories/
    defaults: { _controller: posey.ultimateblog.controller:categories }

posey_ultimateblog_category:
    path: /blog/categories/{cat_id}
    defaults: { _controller: posey.ultimateblog.controller:category }
    requirements:
        "cat_id": \d+

posey_ultimateblog_archive:
    path: /blog/archive/{year}-{month}
    defaults: { _controller: posey.ultimateblog.controller:archive }
    requirements:
        "year": \d+
        "month": \d+

posey_ultimateblog_search:
    path: /blog/search
    defaults: { _controller: posey.ultimateblog.controller:search }

posey_ultimateblog_subscribe:
    path: /blog/subscribe
    defaults: { _controller: posey.ultimateblog.controller:subscribe }

posey_ultimateblog_rss:
    path: /blog/rss
    defaults: { _controller: posey.ultimateblog.controller:rss }