posey_ultimateblog_blog:
    path: /blog
    defaults: { _controller: posey.ultimateblog.controller:blog }

posey_ultimateblog_display_blog:
    path: /blog/{blog_id}
    defaults: { _controller: posey.ultimateblog.controller:display_blog }

posey_ultimateblog_categories:
    path: /categories
    defaults: { _controller: posey.ultimateblog.controller:categories }

posey_ultimateblog_category:
    path: /categories/{cat_id}
    defaults: { _controller: posey.ultimateblog.controller:category }