imports:
    - { resource: tables.yml }

services:
    posey.ultimateblog.admin.controller:
        class: posey\ultimateblog\controller\admin_controller
        arguments:
           - '@user'
           - '@template'
           - '@dbal.conn'
           - '@log'
           - '@config'
           - '@auth'
           - '@controller.helper'
           - '@request'
           - '@pagination'
           - '%core.root_path%'
           - '%core.php_ext%'
           - '%posey.ultimateblog.table.ub.blogs%'
           - '%posey.ultimateblog.table.ub.cats%'

    posey.ultimateblog.controller:
        class: posey\ultimateblog\controller\main_controller
        arguments:
           - '@user'
           - '@config'
           - '@controller.helper'
           - '@request'
           - '%core.root_path%'
           - '%core.php_ext%'
           - '@posey.ultimateblog.core.blog'
           - '@posey.ultimateblog.core.category'
           - '@posey.ultimateblog.core.functions'

    posey.ultimateblog.listener:
        class: posey\ultimateblog\event\listener
        arguments:
           - '@user'
           - '@template'
           - '@dbal.conn'
           - '@config'
           - '@auth'
           - '@controller.helper'
           - '@request'
           - '@path_helper'
           - '%core.root_path%'
           - '%core.php_ext%'
           - '%posey.ultimateblog.table.ub.blogs%'
           - '%posey.ultimateblog.table.ub.cats%'
        tags:
           - { name: event.listener }

    posey.ultimateblog.core.blog:
        class: posey\ultimateblog\core\blog
        arguments:
           - '@user'
           - '@template'
           - '@dbal.conn'
           - '@log'
           - '@config'
           - '@auth'
           - '@controller.helper'
           - '@request'
           - '@pagination'
           - '%core.root_path%'
           - '%core.php_ext%'
           - '%posey.ultimateblog.table.ub.blogs%'
           - '%posey.ultimateblog.table.ub.cats%'
           - '%posey.ultimateblog.table.ub.comments%'
           - '%posey.ultimateblog.table.ub.rating%'
           - '@posey.ultimateblog.core.functions'

    posey.ultimateblog.core.category:
        class: posey\ultimateblog\core\category
        arguments:
           - '@user'
           - '@template'
           - '@dbal.conn'
           - '@log'
           - '@config'
           - '@auth'
           - '@controller.helper'
           - '@request'
           - '@pagination'
           - '%core.root_path%'
           - '%core.php_ext%'
           - '%posey.ultimateblog.table.ub.blogs%'
           - '%posey.ultimateblog.table.ub.cats%'
           - '%posey.ultimateblog.table.ub.rating%'
           - '@posey.ultimateblog.core.functions'

    posey.ultimateblog.core.functions:
        class: posey\ultimateblog\core\functions
        arguments:
            - '@template'
            - '@dbal.conn'
            - '@controller.helper'
            - '@user'
            - '@config'
            - '@auth'
            - '@log'
            - '@request'
            - '@pagination'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%posey.ultimateblog.table.ub.blogs%'
            - '%posey.ultimateblog.table.ub.cats%'
            - '%posey.ultimateblog.table.ub.comments%'
            - '%posey.ultimateblog.table.ub.rating%'