imports:
    - { resource: tables.yml }

services:
    posey.ultimateblog.admin.controller:
        class: posey\ultimateblog\controller\admin_controller
        arguments:
           - @user
           - @template
           - @dbal.conn
           - @log
           - @config
           - @auth
           - @controller.helper
           - @request
           - @pagination
           - %core.root_path%
           - %core.php_ext%
           - %posey.ultimateblog.table.ub.blogs%
           - %posey.ultimateblog.table.ub.cats%

    posey.ultimateblog.controller:
        class: posey\ultimateblog\controller\main_controller
        arguments:
           - @user
           - @template
           - @dbal.conn
           - @log
           - @config
           - @auth
           - @controller.helper
           - @request
           - @pagination
           - %core.root_path%
           - %core.php_ext%
           - %posey.ultimateblog.table.ub.blogs%
           - %posey.ultimateblog.table.ub.cats%
           - %posey.ultimateblog.table.ub.comments%

    posey.ultimateblog.listener:
        class: posey\ultimateblog\event\listener
        arguments:
           - @user
           - @template
           - @dbal.conn
           - @config
           - @auth
           - @controller.helper
           - @request
           - %core.root_path%
           - %core.php_ext%